### ISSUE TITLE
Including BME280 instead of the DHT22 for Humidity, Temperature and air pressure

### ISSUE THREAD

**Issue by h0lz** [toto/homebridge-airrohr#1]
Hi, I'm very happy with the plugin and it works perfect for PM2,5 and PM10 for me.

I'm using a "BME280"(also supported by the AirRohr Software) instead of the default "DHT22" for humidity and temperature (higher accuracy),
and the air pressure as well.

Would it be Possible for the plugin to include these as well?
At least humidity and temperature?
Here is the data.json output from my AirRohr device:

{"software_version": "NRZ-2017-099", "age":"145", "sensordatavalues":[{"value_type":"SDS_P1","value":"6.50"},{"value_type":"SDS_P2","value":"3.20"},{"value_type":"BME280_temperature","value":"6.86"},{"value_type":"BME280_humidity","value":"86.66"},{"value_type":"BME280_pressure","value":"100003.54"},{"value_type":"samples","value":"598753"},{"value_type":"min_micro","value":"231"},{"value_type":"max_micro","value":"505639"},{"value_type":"signal","value":"-82"}]}

I assume that your plugin isn't expecting the value name prefix.
Perhaps something like a wildcard for the prefixes would do?

**Comment by toto** [comment]
Indeed this does not work so far. I will add the BME280 support in the next release. 

Is this data in the sensordaten.info API as well? If so I would appreciate the sensor id (for the temperature part) so I can verify that this also works.

**Comment by toto** [comment]
v1.1 (just published to npm) should fix this and support BME280 data from internal sensors.

**Comment by h0lz** [comment]
Yes, it's all in the Sensordaten API.
Thanks for your work.
