### ISSUE TITLE
Add air pressure from the BME280

### ISSUE THREAD

**Issue by h0lz** [toto/homebridge-airrohr#10]
As mentioned in Issue #1 I'm using the BME280 sensor.
A search in the public data for the sensor shows up more than 1000 hits so the Sensor seems to be relatively common.
In addition to #4 (measurement history via "fakegato") it would be great to have the air pressure in the homebridge data.

**Comment by toto** [comment]
I noticed the air pressure when adding this. However there is no official characteristic for air pressure (quite strange…). So the only way to have this would be to be "Elgato" compatible. It would not show up in the Home app.

**Comment by h0lz** [comment]
The home from Apple sadly lacks many sensors types. The app from Elgato is free so I think there will be a bunch of airrohr user who would appreciate an option for air pressure measurements.

**Comment by toto** [comment]
Fixed in #13. Will be part of the next release.
