### ISSUE TITLE
Publish Air Pressure 

### ISSUE THREAD

**Issue by Womble-1** [toto/homebridge-airrohr#20]
I'm using the BME280, is it possible to publish the air pressure into homekit? 

(Thank you for writing and sharing. All worked 1st time and as documented!)

**Comment by h0lz** [comment]
The BME280 already works with the Elgato App. 
If I remember correctly the Apple Home App doesn’t support air pressure. (Correct me if I’m wrong)

**Comment by toto** [comment]
Correct HomeKit does not have air pressure as a well known value type for some strange reason and it's not supported in the home app. Elgato defined a custom value type and it should be supported

**Comment by Womble-1** [comment]
Agreed.   Thanks. 
Finally found something authoritative here:
https://developer.apple.com/documentation/homekit/hmservicetypethermostat#declarations
