### ISSUE TITLE
kein Update der Sensordaten

### ISSUE THREAD

**Issue by kodibrain** [toto/homebridge-airrohr#23]
Hi,

ich habe seid längerem das Problem dass die aktuellen Daten des Sensors nicht in Home aktualisiert werden. Nach einem neustart der homebridge funktioniert es für ein paar Stunden danach bekomme ich immer nur die selben Werte, die neuen werden nicht aus der data.json gezogen.
Jemand eine Idee an was es liegt?

Die persist.json habe ich bereits gelöscht und das plugin neu installiert, aber ohne Erfolg

**Comment by h0lz** [comment]
Hatte ich ebenfalls. Dachte es läge an meinem Pi-Hole. Aktuell geht alles.

**Comment by kodibrain** [comment]
komisch das ganze zumal es nach einem Neustart einige Stunden funktioniert.
Im error log ist auch kein Eintrag zum plugin

**Comment by honkmaster** [comment]
Meine Lösung war in der Config von .local auf die IP des Airrohr zu ändern.

**Comment by kodibrain** [comment]
Die IP.. So ist es bei mir schon immer in der config eingetragen :(
Problem ist wohl ein anderes

**Comment by Typ1er** [comment]
habe momentan das selbe Problem, ist etwas nervig

**Comment by rudelm** [comment]
Habe das Problem aktuell auch und hatte von Anfang an die Variante mit der IP gewählt, leider werden die Daten auch nicht mehr erfasst. Wenn ich die IP mit der json URL öffne, bekomme ich sofort die Daten, der Sensor ist also auch sofort erreichbar.

Habe allerdings auch von jedem etwas: Mehrere AP (AVM 1750e) mit gleicher SSID im Mesh, einen PiHole und ein DNS suffix mit .local am Ende. Bin für Ideen/Vorschläge offen :)

**Comment by Typ1er** [comment]
Seitdem ich umgestellt habe auf online Abfrage geht es
