### ISSUE TITLE
Different / Custom names for each sensor information

### ISSUE THREAD

**Issue by honkmaster** [toto/homebridge-airrohr#3]
First of all, thanks for this component.

Would it be possible to add a configuration options to have different names for the sensors? Would be very useful, e.g. in a non english environment. Thanks.

P.S.: I am not familiar with JS, otherwise I would have created a PR. Sorry :).

**Comment by toto** [comment]
You can edit all names in the home app on iOS. The names given by the plugin are are just a suggestion used first.

**Comment by honkmaster** [comment]
Thanks. I did not even know that was possible (similar to changing the icons).
