### ISSUE TITLE
No more data pulled using the public API

### ISSUE THREAD

**Issue by pbksol** [toto/homebridge-airrohr#30]
Since a few weeks the plugin fails to receive data using the Public API.

`[AirRohr] Could not get sensor data: Error: Request Failed.
Status Code: 302`

**Comment by roboterm** [comment]
Same here.

**Comment by martinnock** [comment]
For me it works with new URL like this 
http://data.sensor.community/airrohr/v1/sensor/9268/

**Comment by pbksol** [comment]
That URL delivers the exact same JSON content. The plugin fails to parse the data. I have no time to dig deeper. If the plugin is no longer maintained I might do at some time.

**Comment by roboterm** [comment]
The URLs above are correct and the plugin works fine for me now.
I rechecked my config.json and forgot the "/" at the end *shameonme*.

**Comment by roboterm** [comment]
closed by 5d9dd68

**Comment by pbksol** [comment]
So… Der 302 HTTP-Status ist es, woran das Plugin scheitert. Der bisherige API-URL wird umgeleitet und das Plugin erwartet immer einen 200er und scheitert daher. Das war der entscheidende Unterschied – die Rückgabe der Daten über die API war zwar optisch korrekt, aber der HTTP-Code war das Problem. Ich mach hier wieder zu.

**Comment by brandungskieker** [comment]
In my opinion the issue wasn't fixed yet. What's your reason for closing this ticket?

**Comment by roboterm** [comment]
@brandungskieker I changed the example config.json to the new URL.
If you apply these changes to your config the plugin should work.
