### ISSUE TITLE
Webadresse hat sich geändert

### ISSUE THREAD

**Issue by Typ1er** [toto/homebridge-airrohr#33]
Bei mir würde eine Zeitlang gar nichts mehr angezeigt, Wenn man dem Beispiel folgt kommen keine Werte mehr vom Sensor.

Aus http://api.luftdaten.info/v1/sensor/18499/ ist jetzt http://data.sensor.community/airrohr/v1/sensor/18499/ geworden.

Bitte die Beispiel Config anpassen.

**Comment by toto** [comment]
Fixed, thanks for the hint!
