### ISSUE TITLE
Missing: air pressure, WIFI signal strength, WIFI quality

### ISSUE THREAD

**Issue by AarneAarebye** [toto/homebridge-airrohr#36]
Hi ToTo,

just installed homebridge-airrohr.

Temperature, air quality and humidity are displayed. Only air pressure and (optional) the WIFI values are missing.
http://myAirRohr/data.json
{
    "software_version": "NRZ-2020-129", 
    "age":"70", 
    "sensordatavalues": [
        {"value_type":"SDS_P1","value":"3.92"},
        {"value_type":"SDS_P2","value":"1.85"},
        {"value_type":"BME280_temperature","value":"21.29"}, 
        {"value_type":"BME280_pressure","value":"100357.12"}, 
        {"value_type":"BME280_humidity","value":"17.94"},
        {"value_type":"samples","value":"4334655"},
        {"value_type":"min_micro","value":"32"},
        {"value_type":"max_micro","value":"84705"},
        {"value_type":"signal","value":"-75"}
    ]
}

Also in the "Homebridge logs" the pressure data are listed. Except the WIFI one.

I got some warnings during installation also.

>sudo npm install -g homebridge-airrohr
npm WARN deprecated cryptiles@4.1.3: This module has moved and is now available at @hapi/cryptiles. Please update your dependencies as this version is no longer maintained an may contain bugs and security issues.
npm WARN deprecated boom@7.3.0: This module has moved and is now available at @hapi/boom. Please update your dependencies as this version is no longer maintained an may contain bugs and security issues.
npm WARN deprecated hoek@6.1.3: This module has moved and is now available at @hapi/hoek. Please update your dependencies as this version is no longer maintained an may contain bugs and security issues.
+ homebridge-airrohr@1.1.8
added 53 packages from 58 contributors in 10.728s
![IMAGE 2020-04-22 19:48:16](https://user-images.githubusercontent.com/25765996/80015567-3c6d0e00-84d2-11ea-80f8-2c8ec994c049.jpg)
![IMAGE 2020-04-22 19:48:44](https://user-images.githubusercontent.com/25765996/80015598-4858d000-84d2-11ea-8f74-a06e0b5b66f2.jpg)

**Comment by nielsth** [comment]
Air Pressure isn't supported in HomeKit. Neither is Wi-Fi or signal strength. 

The latter could actually be useful info under the details/settings tab of accessories, where battery info is also located. However this is something Apple will need to add to the HomeKit specification first.
